### ISSUE TITLE
new DB-backed minter

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/active_fedora-noid#21]
Reliance on filesystem for statefile prevents horizontal scaling of the application (as we need in HyBox).   Reliance on single path in filesystem also blocks multitenancy.  The solution for either of these is to use a db-backed "statefile".  

**Design questions**

Should this be a separate class here akin to `SynchronizedMinter`? a fork of this project? a totally independent gem? 

For performance, ideally the minter is a stored procedure in the db-layer, to minimize the exclusive lock duration.  Potentially a second implementation might be required in sqlite3 for development (still useless for the production cases mentioned above).  It might need separate code for mysql and postgres.  But introduction of specific db-adapter dependencies in `AF:noid` seems undesirable, or at least a marked shift in the profile of the gem.

If created at a rails engine level (Sufia, CurationConcerns, etc.), the dependency profile there doesn't change (as much), but the reusability of the minter is limited.  

I am leaning towards a separate gem, possibly a separate gem per DB adapter.  I'd welcome some feedback from folks w/ more experience around current noid generation.

**Comment by mjgiarlo** [comment]
I'd be happy to see a `DatabaseBackedMinter` added to AF::Noid, as well as a seam in the `Config` class so that folks can do e.g. the following:

```ruby
# config/initializers/active_fedora-noid.rb
ActiveFedora::Noid.configure do |config|
  config.minter = MyApp::MyCustomMinter
end
```

**Comment by mjgiarlo** [comment]
@atz :speech_balloon: 
> But introduction of specific db-adapter dependencies in AF:noid seems undesirable, or at least a marked shift in the profile of the gem.

Agree.

**Comment by cbeer** [comment]
What about just making this an engine? We could even be exceedingly clever and still make it optional if we wanted.

**Comment by mjgiarlo** [comment]
I'm :cool: with that.

**Comment by atz** [comment]
@mjgiarlo: I think I agree w/ the configuration mechanism.

@cbeer: I don't think routes, assets, being mountable, etc. are fundamental to the feature.  Ideally, this would be usable in non-rails ruby code.  On the other hand, it might make scaffolding easier to have rails/activesupport available, in particular some generators.

**Comment by cbeer** [comment]
No, but Rails would give us database connections, migrations, a nice `ActiveRecord` model that can (de)serialize minter state for us, and shared consistency across other projects. I don't think it imposes too much overhead, and could easily be optional (if we care; I suspect we don't need to, given our current consumers)

**Comment by atz** [comment]
@cbeer: are you saying "this [new gem] should be a rails engine" or "this [existing gem] should be a rails engine"?

**Comment by cbeer** [comment]
Yes, I'd start by making `active_fedora-noid` provide an engine (and, if there's a compelling reason not to force it on everyone, make it optional and do some feature checking to see if `Rails` is around).

**Comment by atz** [comment]
I'm 👌 w/ that, despite it seeming to make it more difficult to break out and provide DB-optimized versions later.

**Comment by mjgiarlo** [comment]
@atz also re: what @cbeer said about "forc[ing] it on everyone," I would be happy to let SemVer help us with that. CC currently pulls in `'~> 1.0'`, and changing AF::Noid to an engine would probably make sense as a 2.0 release. An option to consider if that means less cleverness required.

**Comment by atz** [comment]
OK, I think this settled where to do the development.  Will open other ticket w/ particular design questions.
