### ISSUE TITLE
DB minter design questions

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/active_fedora-noid#24]
The database-backed minter (`db` branch) is coming along well, but there are some design questions that need broader vetting.  

LOCKING:  Obviously we will use a DB transaction, but the transaction only helps for our connection.  The point of the DB for horizontal scalability is that potentially many connections will be concurrent.  What kind of locking do we want to use?
1. [optimistic](http://guides.rubyonrails.org/active_record_querying.html#optimistic-locking) -- downside: race condition, `ActiveRecord::StaleObjectError`
2. [pessimistic](http://guides.rubyonrails.org/active_record_querying.html#pessimistic-locking) -- downside: deadlock
3. db-specific (e.g. `LOCK IN SHARE MODE`) or other?

Pick your poison.  

FAILSAFE: The point of locking is that one way or another only one connection/thread writes to the DB at a time.  That means by design somebody loses (at write time for optimistic, at *read* time for pessimistic).  The `mint` method is designed to loop forever until it gets a novel NOID, so presumably catching the failure there and retrying is OK, but at a certain scale, after a certain amount of failure, cycling forever in race/deadlock is counter-productive.  

So, based on the lock you prefer, what tolerance for failure do we have here?  Raise after 100 `StaleObjectError` or timeout after X to avoid deadlock?

**Comment by jcoyne** [comment]
Pessimistic. I don't see how you could have deadlock if you're locking only on a single resource.

**Comment by grosscol** [comment]
Option 2: lock row from time of access until commit.

I don't think this will impeded the ability of the use case to scale reasonably.

**Comment by atz** [comment]
@jcoyne: in the scope of this engine, I agree, it is the only thing in the DB that it cares about.  In the scope of a consuming application, we can imagine transactions wrapping the minter action that add scope.  But the locking logic can be compact and distinct.

If consensus is for pessimistic locking (fine by me), then what failsafe makes sense? Timeout of 10 seconds?  None?

**Comment by mjgiarlo** [comment]
@atz any downside to choosing "none" for now, 'til we know what we're dealing with?

**Comment by atz** [comment]
Random catastrophic failure under load.  Other than that, no....

**Comment by mjgiarlo** [comment]
I call that "Tuesday."
