### ISSUE TITLE
Discussion: Pick Default Minter

### ISSUE THREAD

**Issue by atz** [projecthydra-labs/active_fedora-noid#28]
The default minter has been the file-based SynchronizedMinter.  With the major version bump and availability of DB-backed minter, do we want to shift the default to that?

**Comment by mjgiarlo** [comment]
Before we shift the default, I'd like to get folks using the new minter for a while. I suspect we (the Hydra-in-a-Box team) could volunteer to try it out as an early adopter, and if we're satisfied, revisit this issue?

Thanks, @atz.

**Comment by mjgiarlo** [comment]
The default minter coming in 2.0.0 will be the db-backed one. Thanks, @atz.
