### ISSUE TITLE
Generator fails with Active Fedora 10.1.0

### ISSUE THREAD

**Issue by jonathandixon** [projecthydra-labs/active_fedora-noid#30]
Running `rails generate active_fedora:noid:install` results in the following error:

```
[WARNING] Could not load generator "generators/active_fedora/noid/install_generator". Error: undefined method `expand_path' for ActiveFedora::File:Class.
/Users/dixonj16/.rvm/gems/ruby-2.3.0/gems/active_fedora-noid-2.0.0.beta1/lib/generators/active_fedora/noid/install_generator.rb:4:in `<class:InstallGenerator>'
/Users/dixonj16/.rvm/gems/ruby-2.3.0/gems/active_fedora-noid-2.0.0.beta1/lib/generators/active_fedora/noid/install_generator.rb:3:in `<module:Noid>'
```

This can be reproduced by creating a new rails app and adding the following gems.

```
gem 'active_fedora-noid', '2.0.0.beta1'
gem 'active-fedora', '10.1.0'
```

**Comment by mjgiarlo** [comment]
@jonathandixon I added a commit to master that may help you here. Try it out? 

Thanks for reporting this. Also, do note that the 2.0.0.beta1 release has other known bugs, such as #29. Until that issue is resolved, YMMV with the beta release; you may want to stick with an earlier release.

**Comment by jonathandixon** [comment]
@mjgiarlo Thanks!

The same issue pops up in `generators/active_fedora/noid/seed_generator`.

**Comment by mjgiarlo** [comment]
@jonathandixon OK, try again. ;) I don't see any other references to `File` in the generators. Let's see where that gets you. If that doesn't sort you out, you may want to use a 1.x version of the gem until we spruce up the beta.

**Comment by jonathandixon** [comment]
Thanks, the generator now completes without error.

**Comment by mjgiarlo** [comment]
Most excellent. I'll close this issue, but feel free to create others if you run into anything else.
