### ISSUE TITLE
Pin for a CurationConcerns issue

### ISSUE THREAD

**Issue by barmintor** [projecthydra-labs/active_fedora-noid#34]
Migrating an object with a 7 digit id was yielding empty path segments in the members URI when CC was configured with the default (noid) id-uri translators. Reverting to AF basic fixed the problem.

Example: 1667751 -> /dev/16/67/75/1//1667751/members

**Comment by mjgiarlo** [comment]
@barmintor What is the right value for your example? Is it ` /dev/16/67/75/1/1667751`? That is, is the problem the double-slash, the one-digit "pair," both, or something else?

**Comment by barmintor** [comment]
The double slash blows up- empty path segments aren't allowed.

**Comment by mjgiarlo** [comment]
Thanks, @barmintor.

**Comment by mjgiarlo** [comment]
@barmintor: Fix on the way.

**Comment by mjgiarlo** [comment]
@barmintor backported to 1.x-stable branch and cut v1.1.2 with the fix (while the 2.x beta process plays out).

**Comment by barmintor** [comment]
Thanks @mjgiarlo!
