### ISSUE TITLE
I need access to push the gem

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/active_fedora-noid#9]
`You do not have permission to push to this gem.`

This gem should probably be added to https://github.com/projecthydra/hydra/blob/master/script/grant_revoke_gem_authority.rb and then @mjgiarlo (the only person with access) can run it.

**Comment by mjgiarlo** [comment]
I didn't touch that script (which probably needs other gems added, some emails added, and some emails removed), but I did add a bunch of the usual suspects as owners of AF::Noid. Closing.
